# Generated by Django 4.2.1 on 2023-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilety',
            fields=[
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('ticket_number', models.IntegerField(blank=True, null=True)),
                ('ticket_category', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_text1', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct1', models.BooleanField(blank=True, null=True)),
                ('answer_text2', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct2', models.BooleanField(blank=True, null=True)),
                ('answer_text3', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct3', models.BooleanField(blank=True, null=True)),
                ('answer_text4', models.CharField(blank=True, max_length=255, null=True)),
                ('is_correct4', models.BooleanField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_tip', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bilety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('id_chapter', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chapter',
                'managed': False,
            },
        ),
    ]
